package gelf.model.elements.attributes;

public enum TimingType {
	COMBINATIONAL,
    COMBINATIONAL_RISE,
    COMBINATIONAL_FALL,
    THREE_STATE_DISABLE,
    THREE_STATE_ENABLE,
    THREE_STATE_DISABLE_RISE,
    THREE_STATE_DISABLE_FALL,
    THREE_STATE_ENABLE_RISE,
    THREE_STATE_ENABLE_FALL;
}
