@startuml
-> DeleteCellListener : actionPerformed(ActionEvent e)
activate DeleteCellListener
DeleteCellListener -> DeleteCommand ** : <<creates>> ArrayList<Cell> cellToDelete
activate DeleteCommand

DeleteCellListener -> DeleteCommand : execute()
participant "parentLibrary : Library" as parentLibrary
participant "cells : ArrayList<Cell>" as cells
loop while cellsToDelete.hasNext()
DeleteCommand -> Cell : getParent()
activate Cell
return parentLibrary library
DeleteCommand -> parentLibrary : getCells()
activate parentLibrary
return ArrayList<Cell> cells
DeleteCommand -> cells : remove(Cell)
activate cells 
return
DeleteCommand -> parentLibrary : getFileData()
activate parentLibrary
return String[]
DeleteCommand -> parentLibrary : setFileData()
activate parentLibrary
return 

DeleteCommand -> Model : getInstance()
activate Model
return instance 
DeleteCommand -> Model : getCurrentProject()
activate Model 
return currentProject
participant "currentProject : Project" as currentProject
DeleteCommand -> currentProject : getOpenedInTextElements()
activate currentProject
return HashSet<Element> openedInTextElements



participant "openedInTextElements : HashSet<Element>" as openedInTextElements
participant "copiedElements : HashSet<Element>" as copiedElements



alt if the cell is opened in text editor
DeleteCommand -> openedInTextElements : remove(Cell)
activate openedInTextElements 
return 
else if the cell is not opened in text editor 
end 

DeleteCommand -> currentProject : getCopiedElements()
activate currentProject
return HashSet<Element> copiedElements

alt if the cell is one of the copied elements 
DeleteCommand -> copiedElements : remove(Cell)
activate copiedElements 
return 
else if the cell is not one of the copied elements
end 

end

DeleteCommand -> currentProject: notify()
activate currentProject

loop for each updatable component 
currentProject -> Updatable : update()
activate Updatable
return 
end

return
return 
return 

@enduml