@startuml FR-4
skinparam responseMessageBelowArrow true
    actor User
    User -> "TreeNode t" ++ : double click
    "TreeNode t" -> "OpenElementListener o" ++ : mouseClicked(MouseEvent e)
    "OpenElementListener o" -> "SubWindow s" ** : SubWindow(element)
    activate "SubWindow s"
    "SubWindow s" -> "Visualizer v" **  : Visualizer(element)
    activate "Visualizer v"
    "Visualizer v" -> "DiagramDirector instance" ++: receiveDiagramData(data)
    note over "DiagramDirector instance", "Visualizer v"#FFAAAA
    See Diagram Creation
    end note
    return diagram
    
    "Visualizer v" -> "DataPanel d" ** : DataPanel(element)
    alt element is library
    "Visualizer v" -> "LibraryPanel l" ** : LibraryPanel(element)
    else element is cell/pin
    "Visualizer v" -> "CellPanel c" ** : CellPanel(element)
    activate "CellPanel c"
    "CellPanel c" -> "CellImageGenerator g" ** : CellImageGenerator()
    "CellPanel c" -> "CellImageGenerator g" ++ : buildCell(inputPins, outputPins)
    return BufferedImage
    destroy "CellImageGenerator g"
    return
    end
    return

    return
    "OpenElementListener o" -> "SubWindowArea a" ++ : addSubWindow(s)
    alt 0 SubWindow object in a
    "SubWindowArea a" -> "SubWindow s" ++ : resize(...) [set to full width of a]
    return
    else 1 SubWindow object in a
    "SubWindowArea a" -> "SubWindow s" ++ : resize(...) [set to half the width of a]
    return
    else 2 SubWindow objects in a
    "SubWindowArea a" -> "SubWindow s" ++ : resize(...) [set to a third the width of a]
    return
    else 3 SubWindow objects in a
    "SubWindowArea a" -> "InfoBar i" ++ : setText(InfoBarID::ERROR, "ERROR:Cannot open more than 3 sub-windows")
    return
    end
    return
    return
    return
@enduml
