@startuml
'Style Settings
skinparam {
    Linetype ortho
    BackgroundColor #bababa
    Shadowing false
    Nodesep 60
    Ranksep 50
}
skinparam Arrow {
    Color #2e2e2e
    Thickness 1.5
}
skinparam CircledCharacter {
    Radius 8
    FontSize 10
}
skinparam class {
    BackgroundColor #d1d1d1
    BorderColor #2e2e2e
    BorderThickness 1.5
    HeaderBackgroundColor #a6a6a6
}
skinparam package {
    BackgroundColor #bcbfd6
    BorderThickness 1.8
}
skinparam Note {
    BackgroundColor #297547
    BorderColor #171a17
    FontColor #e8e8e8
}
package Model {
    !includesub Model.plantuml!DIAGRAM
}
package View {
    !includesub View.plantuml!DIAGRAM
}
package Controller {
    !includesub Controller.plantuml!DIAGRAM
}
'From Controller
EventListener --> CellPanel: > observes
EventListener --> Panel: > observes
EventListener --> TextEditor: > observes
EventListener --> LibraryPanel: > observes
EventListener --> Outliner: > observes
EventListener --> Visualizer: > observes
EventListener --> InfoBar: > observes
EventListener --> Model

EventManager --> Model

Hoverable --> Diagram: > observes

DataUpdateHandler --> DataPanel
DataUpdateHandler --> CellPanel
DataUpdateHandler --> LibraryPanel
DataUpdateHandler --> Diagram
DataUpdateHandler --> Outliner

IObserver -> Model: > observes

@enduml