@startuml
left to right direction

'Style Settings
skinparam {
    Linetype ortho
    BackgroundColor #bababa
    Shadowing false
    Nodesep 60
    Ranksep 50
    
}
skinparam Arrow {
    Color #2e2e2e
    Thickness 1.5
}
skinparam CircledCharacter {
    Radius 8
    FontSize 10
}
skinparam class {
    BackgroundColor #d1d1d1
    BorderColor #2e2e2e
    BorderThickness 1.5
    HeaderBackgroundColor #a6a6a6
}
skinparam package {
    BackgroundColor #bcbfd6
    BorderThickness 1.8
}
skinparam Note {
    BackgroundColor #297547
    BorderColor #171a17
    FontColor #e8e8e8
}

!startsub DIAGRAM
together {
    
    class EventManager{
        -MainWindow view
        -Model model
        -Map<Event, EventListener> events
        +EventManager(MainWindow view, Model model)
        +getListeners(): Map<Event, EventListener>
        +void subscribeListener(EventListener listener)
        +void removeListener(EventListener listener)
        
    }

    enum Event{
    LOAD
    OPEN
    DELETE
    REMOVE
    SAVE
    SAVEAS
    EDIT
    SEARCH
    CREATE
    RENAME
    MERGE
    COPY
    MOVE
    PASTE
    REDO
    UNDO
    SCALE
    COMPARE
    INTERPOLATE
    ADDFILTER
    REMOVEFILTER
    LOADPROJECT
    SETTINGS
    SCSETTINGS
    PRSETTINGS
    LASETTINGS
    
    /'
    ATTRDROPDOWN
    GRAPHDROPDOWN
    SUBATTRDROPDOWN
    PIN
    STATISTICS
    '/
    }


    
}

package listeners{

        class LoadLibraryListener implements ActionListener{
            -Command command
            +LoadLibraryListener()
            +void actionPerformed(ActionEvent e)
            
        }
        
        class OpenElementListener implements ActionListener, TreeSelectionListener{
            -Command command
            -Element element
            +OpenElementListener()
            +void actionPerformed(ActionEvent e)
            +void valueChanged(TreeSelectionEvent e)
        }

        class DeleteCellListener implements ActionListener, TreeSelectionListener{
            -Command command
            -Cell[] cell
            +DeleteCellListener()
            +void actionPerformed(ActionEvent e)
            +void valueChanged(TreeSelectionEvent e)
        }

        class RemoveListener implements ActionListener, TreeSelectionListener{
            -Command command
            -Element[] element
            +RemoveListener()
            +void actionPerformed(ActionEvent e)
            +void valueChanged(TreeSelectionEvent e)
        }

        class RenameListener implements ActionListener, TreeSelectionListener{
            -Command command
            -String newName
            -Element element
            +RenameListener()
            +void actionPerformed(ActionEvent e)
            +void valueChanged(TreeSelectionEvent e)
        }

        class EditListener implements ActionListener, DocumentListener{
            -Command command
            -String oldText
            -String newText
            -Element element
            +EditListener()
            +void actionPerformed(ActionEvent e)
            +void changedUpdate(DocumentEvent e)
        }

        class SearchListener implements TextListener{
            -Model model
            -Panel panel
            +SearchListener(Model model)
            +void textValueChanged(TextEvent e)
        }

        class CreateLibraryListener implements ActionListener{
            -Model model
            +CreateLibraryListener(Model model)
            +void actionPerformed(ActionEvent e)
        }

        class SaveListener implements ActionListener{
            -Model model
            +SaveListener(Model model)
            +void actionPerformed(ActionEvent e)
        }

        class SaveAsListener implements ActionListener{
            -Model model
            +SaveAsListener(Model model)
            +void actionPerformed(ActionEvent e)
        }

        class MergeListener implements ActionListener, TreeSelectionListener{
            -Command command
            -Library[] libraries
            +MergeListener()
            +void actionPerformed(ActionEvent e)
            +void valueChanged(TreeSelectionEvent e)
        }

        class ScaleListener implements ActionListener{
            -Command command
            -Attribute attribute
            -float float
            +ScaleListener()
            +void actionPerformed(ActionEvent e)
            
        }

        class InterpolationListener implements ActionListener{
            -Command command
            -Model model
            +InterpolationListener()
            +void actionPerformed(ActionEvent e)
        }

        class UndoListener implements ActionListener{
            -Command command
            +UndoListener()
            +void actionPerformed(ActionEvent e)
        }

        class RedoListener implements ActionListener{
            -Command command
            +RedoListener()
            +void actionPerformed(ActionEvent e)
        }

        class CompareListener implements ActionListener, TreeSelectionListener{
            -Command command
            -Element element1
            -Element element2
            +CompareListener()
            +void actionPerformed(ActionEvent e)
            +void valueChanged(TreeSelectionEvent e)
        }

        together {
            class MoveListener implements ActionListener, TreeSelectionListener{
                -Command command
                -Element[] element
                +MoveListener()
                +void actionPerformed(ActionEvent e)
                +getElements(): Element[]
            } 

            class CopyListener implements ActionListener, TreeSelectionListener{
                -Command command
                -Element[] element
                +CopyListener()
                +void actionPerformed(ActionEvent e)
                +getElements(): Element[]
            }

            class PasteListener implements ActionListener, TreeSelectionListener{
                -Command command
                -EventListener moveListener
                -EventListener copyListener
                -Library targetLibrary
                +PasteListener()
                +void actionPerformed(ActionEvent e)
            }
        }

        class AddFilterListener implements ActionListener{
            -Command command
            -Filter filter
            +AddFilterListener()
            +void actionPerformed(ActionEvent e)
        }

         class RemoveFilterListener implements ActionListener{
            -Command command
            -Filter filter
            +RemoveFilterListener()
            +void actionPerformed(ActionEvent e)
        }

        
        class LoadProjectListener implements ActionListener{
            -Command command 
            -Model model
            -Project project
            +LoadProjectListener(Model model)
            +void actionPerformed(ActionEvent e)
        }

        class ExportProjectListener implements ActionListener{
            -Command command 
            -Model model 
            +ExportProjectListener(Model model)
            +void actionPerformed(ActionEvent e)

        }

        class SettingsListener implements ActionListener{
            -Model model
            +SettingsListener(Model model)
            +void actionPerformed(ActionEvent e)
        }

        class ShortcutSettingsListener implements KeyListener{
            -Shortcut shorcuts
            +ShortcutSettingsListener(Model model)
            +void actionPerformed(ActionEvent e)
        }

        class PreferencesSettingsListener implements ActionListener{
            -Model model
            +PreferencesSettingsListener(Model model)
            +void actionPerformed(ActionEvent e)
        }

        class LanguageSettingsListener implements ActionListener{
            -Model model
            +LanguageSettingsListener(Model model)
            +void actionPerformed(ActionEvent e)
        }

        /'
        class AttributeDropdownListener implements ActionListener{
            +AttributeDropdownListener()
            +void actionPerformed(ActionEvent e)
        }

        class SubAttributeDropdownListener implements ActionListener{
            +SubAttributeDropdownListener()
            +void actionPerformed(ActionEvent e)
        }

        class GraphDropdownListener implements ActionListener{
            +GraphDropdownListener()
            +void actionPerformed(ActionEvent e)
        }

        class PinSelectListener implements ActionListener{
            +PinSelectListener()
            +void actionPerformed(ActionEvent e)
        }

         class StatisticsListener implements ItemListener{
            +StatisticsListener()
            +void itemStateChanged(ItemEvent e)
        }

        class TabListener implements ActionListener{
            
            +TabListener()
            +void actionPerformed(ActionEvent e)
        }
        '/

    PasteListener -> MoveListener
    PasteListener -> CopyListener

}
!endsub
@enduml