@startuml
left to right direction

'Style Settings
skinparam {
    Linetype ortho
    BackgroundColor #bababa
    Shadowing false
    Nodesep 60
    Ranksep 50
    
}
skinparam Arrow {
    Color #2e2e2e
    Thickness 1.5
}
skinparam CircledCharacter {
    Radius 8
    FontSize 10
}
skinparam class {
    BackgroundColor #d1d1d1
    BorderColor #2e2e2e
    BorderThickness 1.5
    HeaderBackgroundColor #a6a6a6
}
skinparam package {
    BackgroundColor #bcbfd6
    BorderThickness 1.8
}
skinparam Note {
    BackgroundColor #297547
    BorderColor #171a17
    FontColor #e8e8e8
}

!startsub DIAGRAM
together {
    /'class Main{
        +{static} main(String[] args): void
    }'/

    class EventManager{
        -MainWindow view
        -Model model
        -Map<Event, EventListener> events
        -List<IObserver> handlers
        +EventManager(MainWindow view, Model model)
        +initListeners()
        +getListeners(): Map<Event, EventListener>
        +subscribeHandlers()
        +removeListener(EventListener listener)
        +removeHandler(IObserver handler)
        +notifyHandlers(Model model, List<Filter> filters)
        
    }

    enum Event{
    LOAD
    OPEN
    DELETE
    REMOVE
    SAVE
    SAVEAS
    SELECT
    EDIT
    RENAME
    MERGE
    COPY
    MOVE
    PASTE
    REDO
    UNDO
    SCALE
    COMPARE
    INTERPOLATE
    ADDFILTER
    REMOVEFILTER
    LOADPROJECT
    SCSETTINGS
    PRSETTINGS
    LASETTINGS
    ATTRDROPDOWN
    GRAPHDROPDOWN
    SUBATTRDROPDOWN
    PIN
    STATISTICS
    }
    
     
    
    class DataUpdateHandler implements IObserver{
        -Outliner outliner
        -List<Element> elements
        +UpdateHandler(Outliner outliner)
        +update(List<Library> libraries)

    }

    class SettingsUpdateHandler implements IObserver{
        -Panel panel
        +SettingsUpdateHandler(Panel panel)
        +update(Settings settings)

    }


    class FilterUpdateHandler implements IObserver{
        -Panel panel
        +FilterUpdateHandler(Panel panel)
        +update(List<Filter> filters)
    }

    class InterpolationHandler implements IObserver{
        -Panel panel
        +InterpolationHandler(Panel panel)
        +update(Interpolation interpolation)
    }

    

        
    
}

package listeners{

        class LoadLibraryListener implements ActionListener{
            -Command command
            -File file
            -Panel panel
            +LoadLibraryListener(Panel panel)
            +actionPerformed(ActionEvent e)
            
        }
        
        class OpenElementListener implements ActionListener, TreeSelectionListener{
            -Command command
            -Element element
            +OpenElementListener()
            +actionPerformed(ActionEvent e)
            +valueChanged(TreeSelectionEvent e)
        }

        class DeleteCellListener implements ActionListener, TreeSelectionListener{
            -Command command
            -Cell[] cell
            +DeleteCellListener()
            +actionPerformed(ActionEvent e)
            +valueChanged(TreeSelectionEvent e)
        }

        class RemoveListener implements ActionListener, TreeSelectionListener{
            -Command command
            -Element[] element
            +RemoveListener()
            +actionPerformed(ActionEvent e)
            +valueChanged(TreeSelectionEvent e)
        }

        class SelectListener implements TreeSelectionListener{
            -Command command
            -Element[] element
            +SelectListener()
            +valueChanged(TreeSelectionEvent e)
        }

        class RenameListener implements ActionListener, TreeSelectionListener{
            -Command command
            -Element element
            +RenameListener()
            +actionPerformed(ActionEvent e)
            +valueChanged(TreeSelectionEvent e)
        }

        class EditListener implements ActionListener, DocumentListener{
            -Command command
            -String newText
            -Element element
            +EditListener()
            +actionPerformed(ActionEvent e)
            +changedUpdate(DocumentEvent e)
        }

        class SaveListener implements ActionListener{
            -Model model
            +SaveListener(Model model)
            +actionPerformed(ActionEvent e)
        }

        class SaveAsListener implements ActionListener{
            -Model model
            +SaveAsListener(Model model)
            +actionPerformed(ActionEvent e)
        }

        class MergeListener implements ActionListener, TreeSelectionListener{
            -Command command
            -Library[] libraries
            +MergeListener()
            +actionPerformed(ActionEvent e)
            +valueChanged(TreeSelectionEvent e)
        }

        class ScaleListener implements ActionListener{
            -Command command
            -Attribute attribute
            -float float
            +ScaleListener()
            +actionPerformed(ActionEvent e)
            
        }

        class InterpolationListener implements ActionListener{
            -Command command
            +InterpolationListener()
            +actionPerformed(ActionEvent e)
        }

        class UndoListener implements ActionListener{
            -Command command
            +UndoListener()
            +actionPerformed(ActionEvent e)
        }

        class RedoListener implements ActionListener{
            -Command command
            +RedoListener()
            +actionPerformed(ActionEvent e)
        }

        class CompareListener implements ActionListener, TreeSelectionListener{
            -Command command
            +CompareListener()
            +actionPerformed(ActionEvent e)
            +valueChanged(TreeSelectionEvent e)
        }

        class MoveListener implements ActionListener, TreeSelectionListener{
            -Command command
            -Element[] element
            +MoveListener()
            +actionPerformed(ActionEvent e)
            +getElements(): Element[]
        } 

        class CopyListener implements ActionListener, TreeSelectionListener{
            -Command command
            -Element[] element
            +CopyListener()
            +actionPerformed(ActionEvent e)
            +getElements(): Element[]
        }

        class PasteListener implements ActionListener, TreeSelectionListener{
            -Command command
            -EventListener moveListener
            -EventListener copyListener
            -Library targetLibrary
            +PasteListener()
            +actionPerformed(ActionEvent e)
        }

        class AddFilterListener implements ActionListener{
            -Command command
            -Filter filter
            +AddFilterListener()
            +actionPerformed(ActionEvent e)
        }

         class RemoveFilterListener implements ActionListener{
            -Command command
            -Filter filter
            +RemoveFilterListener()
            +actionPerformed(ActionEvent e)
        }

        
        class LoadProjectListener implements ActionListener{
            -Command command 
            -Project project
            +LoadProjectListener()
            +actionPerformed(ActionEvent e)
        }

        

        class StatisticsListener implements ItemListener{
            +StatisticsListener()
            +itemStateChanged(ItemEvent e)
        }

        class ShortcutSettingsListener implements KeyListener{
            -Shortcut shorcuts
            +ShortcutSettingsListener(Shortcuts shortcuts)
            +actionPerformed(ActionEvent e)
        }

        class PreferencesSettingsListener implements ActionListener{
            -Model model
            +PreferencesSettingsListener(Model model)
            +actionPerformed(ActionEvent e)

        }

        class LanguageSettingsListener implements ActionListener{
            -Model model
            +LanguageSettingsListener(Model model)
            +actionPerformed(ActionEvent e)
        }


        class AttributeDropdownListener implements ActionListener{
            +AttributeDropdownListener()
            +actionPerformed(ActionEvent e)
        }

        class SubAttributeDropdownListener implements ActionListener{
            +SubAttributeDropdownListener()
            +actionPerformed(ActionEvent e)
        }

        class GraphDropdownListener implements ActionListener{
            +GraphDropdownListener()
            +actionPerformed(ActionEvent e)
        }

        class PinSelectListener implements ActionListener{
            +PinSelectListener()
            +actionPerformed(ActionEvent e)
        }

        
        /'class TabListener implements ActionListener{
            -
            
            +TabListener(, )
            +actionPerformed(ActionEvent e)
        }
        '/


}
!endsub
@enduml
