@startuml
left to right direction

'Style Settings
skinparam {
    
    BackgroundColor #bababa
    Shadowing false
    Nodesep 60
    Ranksep 50
    groupInheritence 3
}
skinparam Arrow {
    Color #2e2e2e
    Thickness 1.5
}
skinparam CircledCharacter {
    Radius 8
    FontSize 10
}
skinparam class {
    BackgroundColor #d1d1d1
    BorderColor #2e2e2e
    BorderThickness 1.5
    HeaderBackgroundColor #a6a6a6
}
skinparam package {
    BackgroundColor #bcbfd6
    BorderThickness 1.8
}
skinparam Note {
    BackgroundColor #297547
    BorderColor #171a17
    FontColor #e8e8e8
}

package model{
    

    interface IModel{

    }

    class Project implements IModel{

    }

}


package view{
    together {
        interface EventListener 


        interface ActionListener extends EventListener{
            +actionPerformed(ActionEvent e)
        }

        interface TextListener extends EventListener{
            +textValueChanged(TextEvent e)
        }

        interface ItemListener extends EventListener{
            +itemStateChanged(TextEvent e)
        }

        interface DocumentListener extends EventListener{
            +changedUpdate(DocumentEvent e)
            +insertUpdate(DocumentEvent e)
            +removeUpdate(DocumentEvent e)
        }
        
        interface Hoverable
    }

    interface IView{

    }

    class MainWindow implements IView{
        -MenuBar mainMenu

        +MainWindow()
        + {static} void main(String[] args)
        +subscribeListeners(ActionListener listeners)
    }

    class Outliner
    class TextEditor
    class Visualizer
    class InfoBar
    class CellPanel
    class LibraryPanel
    class DataPanel
    class Diagram
}


package controller{

    together {
        class EventManager{
            -IModel model
            -IView view

            +EventManager(IModel project, IView view)
            -initListeners()
        }

        
        
        class Shortcuts {
            Map<Shortcuts, Event>


        }
    }

    package listeners{

            class LoadLibraryListener implements ActionListener{
                -IModel model
                -IView view
                +LoadLibraryListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }
            
            class OpenElementListener implements ActionListener{
                -IModel model
                -IView view
                +OpenElementListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }

            class DeleteCellListener implements ActionListener{
               -IModel model
               -IView view
               +DeleteCellListener(IModel project, IView view)
               +actionPerformed(ActionEvent e)
            }

            class RemoveCellListener implements ActionListener{
                -IModel model
                -IView view
                +RemoveCellListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }

            class SelectListener implements ActionListener{
                -IModel model
                -IView view
                +SelectCellListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }

            class ExpandCollapseListener implements ActionListener{
                -IView view
                +ExpandCollapseListener(IView view)
                +actionPerformed(ActionEvent e)
           
            }
            class RenameListener implements ActionListener{
                -IModel model
                -IView view
                +RenameListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }

            class EditListener implements ActionListener, DocumentListener{
                -IModel model
                -IView view
                +EditListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }

            class SaveListener implements ActionListener{
                -IModel model
                -IView view
               +SaveListener(IModel project, IView view)
               +actionPerformed(ActionEvent e)
            }

            class SaveAsListener implements ActionListener{
                -IModel model
                -IView view
                +SaveAsListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }

            class MergeListener implements ActionListener{
                -IModel model
                -IView view
                +MergeListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }

            class ScaleListener implements ActionListener{
                -IModel model
                -IView view
                +ScaleListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }

            class InterpolationListener implements ActionListener{
                -IModel model
                -IView view
                +InterpolationListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }

            class SettingsListener implements ActionListener{
                -IView view
                +SettingsListener(IView view)
                +actionPerformed(ActionEvent e)
            }

            class UndoListener implements ActionListener{
               -IModel model
               -IView view
               +UndoListener(IModel project, IView view)
               +actionPerformed(ActionEvent e)
            }

            class RedoListener implements ActionListener{
                -IModel model
                -IView view
                +RedoListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }

            class StatisticsListener implements ItemListener{
               -IView view
               -IModel model
               +StatisticsListener(IModel project, IView view)
               +actionPerformed(ActionEvent e)
            }

            class PopUpListener implements ActionListener{
                -IView view
                +PopUpHandler(IView view)
                +actionPerformed(ActionEvent e)
            }

            class SearchListener implements TextListener{
                -IView view
                +SearchListener(IView view)
                +actionPerformed(ActionEvent e)
            }

            class CompareListener implements ActionListener{
                -IModel model
                -IView view
                +CompareListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }

            class MoveListener implements ActionListener{
                -IModel model
                -IView view
                +MoveListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            } 

            class CopyListener implements ActionListener{
                -IModel model
                -IView view
                +CopyListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }

            class InfoListener implements ActionListener{
                -IView view
                +InfoListener(IView view)
                +actionPerformed(ActionEvent e)
            }

            class PasteListener implements ActionListener{
                -IModel model
                -IView view
                +PasteListener(IModel project, IView view)
                +actionPerformed(ActionEvent e)
            }

            class HoverListener implements Hoverable{
                -IModel model 
                -IView view
                +HoverListener(IModel project, IView view)
                +...()
            }

            class FilterListener implements ActionListener{
                -IModel model
                -IView view
                +FilterListener(IModel project, IView view)
            }


    }

    

}   
       
    EventListener --> CellPanel: > observes
    EventListener --> MainWindow: > observes
    EventListener --> TextEditor: > observes
    EventListener --> LibraryPanel: > observes
    EventListener --> Outliner: > observes
    EventListener --> Visualizer: > observes
    EventListener --> InfoBar: > observes
    EventListener --> Project

    EventManager --> IModel

    Hoverable --> Diagram: > observes
  
   
            

       


@enduml