@startuml
-> ScaleListener : actionPerformed(ActionEvent e)
activate ScaleListener
ScaleListener -> ScaleCommand ** : <<creates>> Attribute attribute, float value

ScaleListener -> ScaleCommand : execute()
activate ScaleCommand 

ScaleCommand -> Model : getInstance()
activate Model
return instance 

ScaleCommand -> Model : getCurrentProject()
activate Model 
return currentProject
participant "currentProject : Project" as currentProject

alt attribute has 1 dimensional values
ScaleCommand -> Attribute : getValues()
activate Attribute
return float[] values
ScaleCommand -> Attribute : setValues(float[])
activate Attribute
return
else attribute has 2 dimensional values
ScaleCommand -> Attribute : getValues()
activate Attribute
return float[][] values
ScaleCommand -> Attribute : setValues(float[][])
activate Attribute
return
end

ScaleCommand -> currentProject: notify()
activate currentProject

loop for each updatable component 
currentProject -> Updatable : update()
activate Updatable
return 
end

return
return 
return


@enduml