@startuml PackageDiagram
'Style Settings
skinparam {
    Linetype ortho
    BackgroundColor #bababa
    Shadowing false
    Nodesep 10
    Ranksep 10
}
skinparam Arrow {
    Color #2e2e2e
    Thickness 1.5
}
skinparam CircledCharacter {
    Radius 8
    FontSize 10
}
skinparam class {
    BackgroundColor #d1d1d1
    BorderColor #2e2e2e
    BorderThickness 1.5
    HeaderBackgroundColor #a6a6a6
}
skinparam package {
    BackgroundColor #bcbfd6
    BorderThickness 1.8
}
skinparam Note {
    BackgroundColor #297547
    BorderColor #171a17
    FontColor #e8e8e8
}
'Content
package Model{
    package Elements{
        package Attributes
    }
    package Exceptions
    package Commands
    package Parsers
    package Compilers
    package Project
    'Relations
}
package View {
    package Components
    package Composites
    package Diagrams{
        package Diagrams.Overlayer
        package Diagrams.Components
        package Diagram.Data
        package Diagram.Type
        package Diagram.Indicator
        package Diagram.Builder
    }
    package Representation
    'Relations
    Composites --> Components
    Composites --> Representation
    Composites --> Diagrams
}
package Controller {
    package Listeners
    'Relations
}
'Relations
Controller -- View
Controller -- Model
View --> Model
Model --> View
@enduml